#!/bin/bash

[[ "${DEBUG}" == 'true' ]] && set -o xtrace
set -o errexit
set -o pipefail
set -o nounset

echo "$(tput bold)dotfiles export-vscode-extensions$(tput sgr0)"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
readonly DIR
readonly DRY_RUN=true
readonly IMPORTFILE="import-vscode-extensions.sh"
readonly DESTINATION_PATH="${DIR}/${IMPORTFILE}"

cd "${DIR}"
touch "${DESTINATION_PATH}"
chmod +x "${DESTINATION_PATH}"

{
  echo "#!/bin/bash" >"${DESTINATION_PATH}"
  echo ""
  echo "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY."
  echo "# TO UPDATE THIS FILE RUN $(basename "$0")"

  echo "echo \"$(tput bold)dotfiles import-vscode-extensions$(tput sgr0)\""
  code --list-extensions | xargs -L 1 echo code --install-extension
} >>"${DESTINATION_PATH}"
