#!/usr/bin/env bash

[[ "${DEBUG}" == 'true' ]] && set -o xtrace
set -o errexit
set -o pipefail
set -o nounset

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
readonly DRY_RUN=true
readonly IMPORTFILE="import-vscode-extensions.sh"
readonly DESTPATH="${DIR}/${IMPORTFILE}"


cd "${DIR}"
touch "${DESTPATH}"
chmod +x "${DESTPATH}"

echo "#!/usr/bin/env bash" > "${DESTPATH}"
echo "" >> "${DESTPATH}"
echo "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY." >> "${DESTPATH}"
echo "# RUN $(basename "$0") INSTEAD" >> "${DESTPATH}"

echo "echo \"Importing VSCode extensions…\"" >> "${DESTPATH}"
code --list-extensions | xargs -L 1 echo code --install-extension >> "${DESTPATH}"
echo "echo \"Done.\"" >> "${DESTPATH}"
