#!/usr/bin/env bash

# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# TO UPDATE THIS FILE RUN export-vscode-extensions.sh
echo "Importing VSCode extensions…"
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.project-manager
code --install-extension alexcvzz.vscode-sqlite
code --install-extension bibhasdn.unique-lines
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension burkeholland.simple-react-snippets
code --install-extension carlosjs23.vscode-yarn-script
code --install-extension castwide.solargraph
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension DeepInThought.vscode-shell-snippets
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-close-tag
code --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --install-extension humao.rest-client
code --install-extension ikappas.phpcs
code --install-extension karigari.chat
code --install-extension killalau.vscode-liquid-snippets
code --install-extension kokororin.vscode-phpfmt
code --install-extension lkytal.coffeelinter
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension misogi.ruby-rubocop
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension neilbrayfield.php-docblocker
code --install-extension neilding.language-liquid
code --install-extension nidu.copy-json-path
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension planbcoding.vscode-react-refactor
code --install-extension pnp.polacode
code --install-extension rafamel.subtle-brackets
code --install-extension rebornix.ruby
code --install-extension robinbentley.sass-indented
code --install-extension sburg.vscode-javascript-booster
code --install-extension sdras.night-owl
code --install-extension shinnn.stylelint
code --install-extension th7org.eco
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vsmobile.vscode-react-native
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
echo "Done."
